extra-keys = [[ \
  {macro: "CTRL t", display: "NS", popup: {macro: "CTRL n", display: "NS-Alt"}} \
]]



# Set the cursor style: 'block', 'underline', or 'bar'
terminal-cursor-style=bar
bell-character=ignore
allow-external-apps=true


shortcut.create-session = ctrl + t
shortcut.next-session = ctrl + 2
shortcut.previous-session = ctrl + 1
shortcut.rename-session = ctrl + n